export default {
  login: 'pad6y',
  id: 66825118,
  node_id: 'MDQ6VXNlcjY2ODI1MTE4',
  avatar_url: 'https://avatars.githubusercontent.com/u/66825118?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/pad6y',
  html_url: 'https://github.com/pad6y',
  followers_url: 'https://api.github.com/users/pad6y/followers',
  following_url: 'https://api.github.com/users/pad6y/following{/other_user}',
  gists_url: 'https://api.github.com/users/pad6y/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/pad6y/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/pad6y/subscriptions',
  organizations_url: 'https://api.github.com/users/pad6y/orgs',
  repos_url: 'https://api.github.com/users/pad6y/repos',
  events_url: 'https://api.github.com/users/pad6y/events{/privacy}',
  received_events_url: 'https://api.github.com/users/pad6y/received_events',
  type: 'User',
  site_admin: false,
  name: 'Paddy Wong',
  company: null,
  blog: 'www.pad6y.com',
  location: 'Gateshead/ Newcastle',
  email: null,
  hireable: null,
  bio: 'Fullstack Web App Developer',
  twitter_username: null,
  public_repos: 20,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: '2020-06-12T09:25:02Z',
  updated_at: '2022-08-08T10:40:03Z',
};
